export const mockUserTab = [
  {
    user_id: 'dashyhd87ahx7&ASHM*&hs78adh87ashm,8dasd78,0u8adsu,0S&)H',
    full_name: 'Ana Silva',
    email: 'ana.silva@camara.gov.br',
    phone: '95340350096',
    status: 'Ativo',
    cep: '79826110',
    address: 'Rua Toshinobu Katayama',
    city: 'Dourados',
    state: 'MS',
    number: '05',
    created_at: new Date(),
    updated_at: new Date(),
    role: [
      {
        name: 'Atendente',
        id: 'hs78adh87ashm,8dasd78,0u8adsu,0S&)Hdashyhd87ahx7&ASHM*&',
      },
    ],
    document: '93783059038',
    documentFile: 'https://example.com/',
    birth_date: new Date(),
    gender: 'male',
  },
  {
    user_id: '7ashm,8da8adsu8asd78,078,0udsu,0S&)H7ashm,8dasdu,0S&)H',
    full_name: 'Carlos Pereira',
    email: 'carlos.oliveira@camara.gov.br',
    phone: '95340350096',
    status: 'Ativo',
    cep: '74973702',
    address: 'Estrada B',
    city: 'Aparecida de Goiânia',
    state: 'GO',
    number: '02',
    created_at: new Date(),
    updated_at: new Date(),
    role: [
      {
        name: 'administrador',
        id: 'hs78adh87ashm,8dasd78,S&)hHdas0u8adsu,0yhd87ahx7&ASHM*&',
      },
    ],
    document: '63490297040',
    documentFile: 'https://example.com/',
    birth_date: new Date(),
    gender: 'female',
  },
  {
    user_id: '7ashm,8da8adsu8asd78,078,0udsu,0S&)H7ashm,8dasdu,0S&)H',
    full_name: 'Mariana Santos',
    email: 'mariana.santos@camara.gov.br',
    phone: '95340350096',
    status: 'Ativo',
    cep: '74973702',
    address: 'Estrada B',
    city: 'Aparecida de Goiânia',
    state: 'GO',
    number: '02',
    created_at: new Date(),
    updated_at: new Date(),
    role: [
      {
        name: 'Atendente',
        id: 'hs78adh87ashm,8dasd78,S&)hHdas0u8adsu,0yhd87ahx7&ASHM*&',
      },
    ],
    document: '63490297040',
    documentFile: 'https://example.com/',
    birth_date: new Date(),
    gender: 'female',
  },
  {
    user_id: '7ashm,8da8adsu8asd78,078,0udsu,0S&)H7ashm,8dasdu,0S&)H',
    full_name: 'Pedro Costa',
    email: 'pedro.costa@camara.gov.br',
    phone: '95340350096',
    status: 'Inativo',
    cep: '74973702',
    address: 'Estrada B',
    city: 'Aparecida de Goiânia',
    state: 'GO',
    number: '02',
    created_at: new Date(),
    updated_at: new Date(),
    role: [
      {
        name: 'Atendente',
        id: 'hs78adh87ashm,8dasd78,S&)hHdas0u8adsu,0yhd87ahx7&ASHM*&',
      },
    ],
    document: '63490297040',
    documentFile: 'https://example.com/',
    birth_date: new Date(),
    gender: 'female',
  },
  {
    user_id: '7ashm,8da8adsu8asd78,078,0udsu,0S&)H7ashm,8dasdu,0S&)H',
    full_name: 'Juliana Lima',
    email: 'juliana.lima@camara.gov.br',
    phone: '95340350096',
    status: 'Ativo',
    cep: '74973702',
    address: 'Estrada B',
    city: 'Aparecida de Goiânia',
    state: 'GO',
    number: '02',
    created_at: new Date(),
    updated_at: new Date(),
    role: [
      {
        name: 'Gestor',
        id: 'hs78adh87ashm,8dasd78,S&)hHdas0u8adsu,0yhd87ahx7&ASHM*&',
      },
    ],
    document: '63490297040',
    documentFile: 'https://example.com/',
    birth_date: new Date(),
    gender: 'female',
  },
];

export const mockServiceTab = [
  {
    id: 'a1b2c3d4-e5f6-7890-ab12-cdef34567890',
    requested: false,
    name: 'Retirada de Documento',
    estimatedTime: 5,
    schedule: 'amanha',
    documents: 3,
    rating: 5,
    ratingQuantity: 430,
    description: 'Retirada do RG Pet do Totó',
    category: 'text',
    availability: true,
    addedFields: [
      {
        label: 'Tipo de campo',
        placeholder: 'Texto',
        type: 'select',
        hint: 'Mais informações',
        required: true,
        options: ['Opção 1', 'Opção 2'],
      },
    ],
    permissions: [
      {
        name: 'Administradores',
        value: 'Completo',
      },
      {
        name: 'Atendimento geral',
        value: 'Visualizar',
      },
    ],
    createdAt: '2025-04-28T16:38:13.014Z',
    updatedAt: '2025-04-28T16:38:13.019Z',
  },
];

export const activityLog = [
  {
    date: '2020-05-20T15:58:52.062Z',
    email: 'carlos.oliveira@camara.gov.br',
    action: 'Criação de serviços',
    user: 'Carlos Oliveira',
    os: 'Windows 10',
    browser: 'Chrome 98.0.4758.102',
    ip: '192.168.1.105',
  },
  {
    date: '2022-03-19T15:40:52.062Z',
    email: 'marcus.oliveira@camara.gov.br',
    action: 'Criação de serviços',
    user: 'Marcus Oliveira',
    os: 'Linux',
    browser: 'Chrome 29.0.4587.012',
    ip: '192.168.1.222',
  },
  {
    date: '2025-02-18T15:50:52.062Z',
    email: 'trala.oliveira@camara.gov.br',
    action: 'Criação de serviços',
    user: 'Trala',
    os: 'Windows 10',
    browser: 'Chrome 90.0.4758.102',
    ip: '192.168.1.333',
  },
];
